[package]
name = "cchashmap"
version = "0.1.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]

[features]
unstable = ["compiletest_rs"]

[dependencies]
byteorder = "*"
compiletest_rs = { version = "*", optional = true }
libc = "*"
quickcheck = "*"
time = "*"
